// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// CAPER_rcpp
Rcpp::List CAPER_rcpp(const arma::mat& X_c, const arma::mat& X_s, const int k1, const int k2, const double sigma_c, const double sigma_s, const int max_iter, const double epsilon, const bool verbose);
RcppExport SEXP _CAPER_CAPER_rcpp(SEXP X_cSEXP, SEXP X_sSEXP, SEXP k1SEXP, SEXP k2SEXP, SEXP sigma_cSEXP, SEXP sigma_sSEXP, SEXP max_iterSEXP, SEXP epsilonSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_c(X_cSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_s(X_sSEXP);
    Rcpp::traits::input_parameter< const int >::type k1(k1SEXP);
    Rcpp::traits::input_parameter< const int >::type k2(k2SEXP);
    Rcpp::traits::input_parameter< const double >::type sigma_c(sigma_cSEXP);
    Rcpp::traits::input_parameter< const double >::type sigma_s(sigma_sSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(CAPER_rcpp(X_c, X_s, k1, k2, sigma_c, sigma_s, max_iter, epsilon, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CAPER_CAPER_rcpp", (DL_FUNC) &_CAPER_CAPER_rcpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_CAPER(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
