# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CAPER_rcpp <- function(X_c, X_s, k1, k2, sigma_c, sigma_s, max_iter, epsilon, verbose = FALSE) {
    .Call(`_CAPER_CAPER_rcpp`, X_c, X_s, k1, k2, sigma_c, sigma_s, max_iter, epsilon, verbose)
}

